# Generated by Django 2.1.5 on 2019-03-30 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20190330_0733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='count_of_download',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
