# Generated by Django 2.1.5 on 2019-04-23 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20190330_0749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=11),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=11),
        ),
        migrations.AlterField(
            model_name='product',
            name='super_price',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=11, null=True),
        ),
    ]
