# Generated by Django 2.1.5 on 2019-03-28 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20190320_0937'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=200)),
                ('mobile', models.CharField(blank=True, max_length=11)),
                ('message', models.TextField()),
            ],
        ),
    ]
