# Generated by Django 2.1.5 on 2019-03-28 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Payment_log',
            new_name='PaymentLog',
        ),
    ]
