# Generated by Django 2.1.5 on 2019-03-28 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20190328_0728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='files',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_gallery',
        ),
    ]
