# Generated by Django 2.1.1 on 2019-09-30 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20190423_0653'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-id',)},
        ),
        migrations.AddField(
            model_name='order',
            name='amount',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
