# Generated by Django 2.1.1 on 2019-09-30 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20190930_0811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_tool',
        ),
        migrations.AddField(
            model_name='order',
            name='authority',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='refId',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
