# Generated by Django 2.1.5 on 2019-03-28 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20190328_0731'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image_gallery',
            new_name='ImageGallery',
        ),
    ]
