# Generated by Django 3.0.7 on 2020-07-22 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='reply',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
