# Generated by Django 2.2.14 on 2020-08-30 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_comment_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
