# Generated by Django 2.2 on 2020-07-28 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistic',
            name='path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
